### ISSUE TITLE
프로젝트 설정

### ISSUE THREAD

**Issue by byhhh2** [youtube-comment-search/web#1]
### 이슈 

https://github.com/youtube-comment-search/wiki/issues/2
프로젝트 기본 설정 

### TODO 

- [x] discord webhook 연결
- [x] issue template 작성 + label
- [x] wiki issue 생성 github action 작성 
- [x] cra + typescript + axios + msw + eslint
- [x] github pages 배포 

### 기타 

node 18.16.0
npm 9.5.1
